import React, { createContext, useContext, useState } from "react";

const INITIAL_CAMPAIGNS = [
  {
    id: "CP-001",
    judul: "Promo Scaling Gratis",
    deskripsi: "Dapatkan scaling gigi GRATIS untuk pasien baru yang mendaftar bulan ini. Syarat & ketentuan berlaku.",
    badge: "Gratis",
    warna: "from-teal-500 to-teal-700",
    icon: "🦷",
    berlakuHingga: "2026-06-30",
    status: "Aktif",
    targetMembership: ["Semua"],
    syarat: ["Pasien baru pertama kali", "Berlaku 1x per pasien", "Wajib daftar akun terlebih dahulu"],
  },
  {
    id: "CP-002",
    judul: "Member Referral Bonus",
    deskripsi: "Ajak teman dan dapatkan diskon 20% untuk perawatan berikutnya. Teman yang diajak juga dapat diskon 10%.",
    badge: "Diskon 20%",
    warna: "from-orange-400 to-orange-600",
    icon: "🎁",
    berlakuHingga: "2026-07-31",
    status: "Aktif",
    targetMembership: ["Gold", "Platinum"],
    syarat: ["Member Gold atau Platinum", "Teman harus mendaftar dengan kode referral", "Diskon berlaku setelah teman menyelesaikan perawatan pertama"],
  },
  {
    id: "CP-003",
    judul: "Cicilan 0% Behel",
    deskripsi: "Pasang behel sekarang bayar nanti! Cicilan 0% hingga 12 bulan untuk pemasangan behel metal dan ceramic.",
    badge: "Cicilan 0%",
    warna: "from-blue-500 to-blue-700",
    icon: "💳",
    berlakuHingga: "2026-08-31",
    status: "Aktif",
    targetMembership: ["Semua"],
    syarat: ["Minimal DP 30%", "Berlaku untuk behel metal & ceramic", "Pembayaran via kartu kredit partner"],
  },
  {
    id: "CP-004",
    judul: "Diskon Whitening 30%",
    deskripsi: "Senyum lebih cerah dengan harga lebih hemat! Diskon 30% untuk whitening laser dan bleaching.",
    badge: "Diskon 30%",
    warna: "from-yellow-400 to-yellow-600",
    icon: "✨",
    berlakuHingga: "2026-06-15",
    status: "Aktif",
    targetMembership: ["Silver", "Gold", "Platinum"],
    syarat: ["Member Silver ke atas", "Tidak bisa digabung dengan promo lain", "Berlaku Senin–Jumat saja"],
  },
  {
    id: "CP-005",
    judul: "Konsultasi Gratis Pasien Baru",
    deskripsi: "Kunjungan pertama? Konsultasi dengan dokter spesialis kami sepenuhnya GRATIS tanpa syarat apapun.",
    badge: "100% Gratis",
    warna: "from-green-500 to-green-700",
    icon: "👨‍⚕️",
    berlakuHingga: "2026-12-31",
    status: "Aktif",
    targetMembership: ["Semua"],
    syarat: ["Berlaku untuk kunjungan pertama saja", "Tidak termasuk tindakan medis", "Wajib booking terlebih dahulu"],
  },
];

const INITIAL_DOCTORS = [
  {
    id: "DR-001",
    nama: "drg. Amanda",
    spesialis: "Orthodontist",
    noHp: "081223344556",
    email: "amanda@dentiva.com",
    jadwal: "Senin - Jumat",
    status: "Active",
    keahlian: ["Pemasangan Behel", "Retainer & Aligner", "Koreksi Gigitan", "Konsultasi Ortodonti"],
    pendidikan: [
      { tahun: "2019", institusi: "Universitas Indonesia", gelar: "Spesialis Ortodonti" },
      { tahun: "2015", institusi: "Universitas Padjadjaran", gelar: "Sarjana Kedokteran Gigi" },
    ],
  },
  {
    id: "DR-002",
    nama: "drg. Reza",
    spesialis: "General Dentist",
    noHp: "081334455667",
    email: "reza@dentiva.com",
    jadwal: "Selasa - Sabtu",
    status: "Active",
    keahlian: ["Tambal Gigi", "Cabut Gigi", "Scaling & Pembersihan", "Pemeriksaan Rutin"],
    pendidikan: [
      { tahun: "2017", institusi: "Universitas Gadjah Mada", gelar: "Sarjana Kedokteran Gigi" },
      { tahun: "2018", institusi: "PDGI Jakarta", gelar: "Sertifikasi Dokter Gigi Umum" },
    ],
  },
  {
    id: "DR-003",
    nama: "drg. Sinta",
    spesialis: "Cosmetic Dentist",
    noHp: "081445566778",
    email: "sinta@dentiva.com",
    jadwal: "Senin, Rabu, Jumat",
    status: "Inactive",
    keahlian: ["Veneer Gigi", "Whitening & Bleaching", "Smile Design", "Crown & Bridge"],
    pendidikan: [
      { tahun: "2020", institusi: "Universitas Airlangga", gelar: "Spesialis Kedokteran Gigi Estetik" },
      { tahun: "2016", institusi: "Universitas Brawijaya", gelar: "Sarjana Kedokteran Gigi" },
    ],
  }
];


const INITIAL_PATIENTS = [
  {
    // ── 1. Identitas Pasien ──────────────────────────
    id: "PS-001",
    nama: "Andi Pratama",
    jenisKelamin: "L",
    tanggalLahir: "2001-03-15",
    umur: 25,
    fotoProfil: null,
    // ── 2. Kontak ────────────────────────────────────
    noHp: "081234567890",
    email: "andi.pratama@gmail.com",
    alamat: "Jl. Sudirman No. 12, Pekanbaru",
    kotaProvinsi: "Pekanbaru, Riau",
    // ── 3. Akun / Membership ─────────────────────────
    tanggalDaftar: "2024-01-10",
    statusMember: "Premium",
    levelMembership: "Gold",
    statusAktif: true,
    // ── 4. Riwayat Interaksi ─────────────────────────
    riwayatKomplain: [
      { id: "C-001", tanggal: "2026-05-28", isi: "Antrian terlalu lama, sudah menunggu lebih dari 1 jam", status: "Pending", prioritas: "High" },
      { id: "C-002", tanggal: "2026-03-05", isi: "Antrian terlalu lama", status: "Resolved", prioritas: "Medium" },
    ],
    chatHistory: [
      { id: 1, text: "Halo dok, saya mau tanya jadwal kontrol saya", sender: "patient", time: "10:25", tanggal: "2026-05-29" },
      { id: 2, text: "Halo Andi, jadwal kontrol Anda adalah Jumat besok jam 14:00", sender: "admin", time: "10:28", tanggal: "2026-05-29" },
      { id: 3, text: "Terima kasih dokter!", sender: "patient", time: "10:30", tanggal: "2026-05-29" }
    ],
    lastChatMessage: "Terima kasih dokter!",
    lastChatTime: "10:30",
    unreadCount: 0,
    feedbackReview: { rating: 5, komentar: "Pelayanan sangat baik dan ramah!", tanggal: "2026-05-20" },
    catatanAdmin: "Pasien VIP, prioritaskan jadwal.",
    // ── 5. Data Transaksi ─────────────────────────────
    riwayatPerawatan: [
      { tanggal: "2026-05-20", tindakan: "Scaling Gigi", dokter: "drg. Amanda", biaya: 350000, metode: "Transfer Bank" },
      { tanggal: "2026-03-10", tindakan: "Konsultasi & Pemeriksaan", dokter: "drg. Amanda", biaya: 150000, metode: "Tunai" },
      { tanggal: "2025-12-05", tindakan: "Scaling Gigi", dokter: "drg. Reza", biaya: 350000, metode: "QRIS" },
    ],
    totalTransaksi: 850000,
    metodePembayaran: "Transfer Bank",
    jenisPerawatan: "Scaling",
    terakhirKunjungan: "2026-05-20",
    // ── 6. Aktivitas User ─────────────────────────────
    loginTerakhir: "2026-05-29T08:30:00",
    deviceDigunakan: "Android - Samsung Galaxy S23",
    durasiPenggunaan: "45 menit",
    // ── 7. Marketing & Engagement ─────────────────────
    sumberUser: "Google Ads",
    campaignDiikuti: ["Promo Scaling Gratis", "Member Referral"],
    statusPromo: "Aktif",
    // ── Legacy fields ─────────────────────────────────
    keluhan: "Gigi sensitif & karang gigi",
    treatment: "Scaling",
    dokter: "drg. Amanda",
    status: "Active",
    jadwalKontrol: { tanggal: "2026-06-20", keterangan: "Kontrol Scaling & Pemeriksaan Rutin" },
  },
  {
    id: "PS-002",
    nama: "Siti Nurhaliza",
    jenisKelamin: "P",
    tanggalLahir: "1996-07-22",
    umur: 30,
    fotoProfil: null,
    noHp: "081345678901",
    email: "siti.nurhaliza@yahoo.com",
    alamat: "Jl. Pahlawan No. 5, Bangkinang",
    kotaProvinsi: "Kampar, Riau",
    tanggalDaftar: "2024-06-15",
    statusMember: "Regular",
    levelMembership: "Silver",
    statusAktif: true,
    riwayatKomplain: [
      { id: "C-003", tanggal: "2026-05-27", isi: "Dokter terlambat datang, tidak ada pemberitahuan sebelumnya", status: "In Progress", prioritas: "Medium" }
    ],
    chatHistory: [
      { id: 1, text: "Dok, untuk scaling gigi berapa lama prosesnya?", sender: "patient", time: "15:20", tanggal: "2026-05-27" },
      { id: 2, text: "Proses scaling sekitar 30-45 menit Siti", sender: "admin", time: "15:25", tanggal: "2026-05-27" },
      { id: 3, text: "Baik, saya akan datang tepat waktu", sender: "patient", time: "15:30", tanggal: "2026-05-27" }
    ],
    lastChatMessage: "Baik, saya akan datang tepat waktu",
    lastChatTime: "15:30",
    unreadCount: 0,
    feedbackReview: { rating: 4, komentar: "Dokternya sabar dan teliti.", tanggal: "2026-05-01" },
    catatanAdmin: "Alergi obat bius merk X, gunakan alternatif.",
    riwayatPerawatan: [
      { tanggal: "2026-05-01", tindakan: "Tambal Gigi (Komposit)", dokter: "drg. Reza", biaya: 400000, metode: "QRIS" },
      { tanggal: "2026-04-10", tindakan: "Rontgen Gigi", dokter: "drg. Reza", biaya: 200000, metode: "Tunai" },
    ],
    totalTransaksi: 600000,
    metodePembayaran: "QRIS",
    jenisPerawatan: "Tambal Gigi",
    terakhirKunjungan: "2026-05-01",
    loginTerakhir: "2026-05-28T14:20:00",
    deviceDigunakan: "iOS - iPhone 14",
    durasiPenggunaan: "30 menit",
    sumberUser: "Instagram",
    campaignDiikuti: ["Diskon Lebaran 2026"],
    statusPromo: "Aktif",
    keluhan: "Gigi berlubang sebelah kanan",
    treatment: "Tambal Gigi",
    dokter: "drg. Reza",
    status: "Waiting",
    jadwalKontrol: { tanggal: "2026-06-01", keterangan: "Kontrol Tambal Gigi" },
  },
  {
    id: "PS-003",
    nama: "Budi Santoso",
    jenisKelamin: "L",
    tanggalLahir: "1981-11-08",
    umur: 45,
    fotoProfil: null,
    noHp: "085234567890",
    email: "budi.santoso@gmail.com",
    alamat: "Jl. Merdeka No. 88, Dumai",
    kotaProvinsi: "Dumai, Riau",
    tanggalDaftar: "2023-09-20",
    statusMember: "Premium",
    levelMembership: "Platinum",
    statusAktif: true,
    riwayatKomplain: [
      { id: "C-004", tanggal: "2025-11-10", isi: "Hasil whitening kurang merata", status: "Resolved", prioritas: "Medium" },
      { id: "C-005", tanggal: "2026-01-05", isi: "Jadwal dokter tidak sesuai", status: "Resolved", prioritas: "Low" },
    ],
    chatHistory: [
      { id: 1, text: "Pak, hasil whitening sudah sempurna, terima kasih!", sender: "patient", time: "16:10", tanggal: "2026-04-20" },
      { id: 2, text: "Sama-sama Pak Budi. Jangan lupa kontrol 6 bulan lagi ya", sender: "admin", time: "16:15", tanggal: "2026-04-20" }
    ],
    lastChatMessage: "Sama-sama Pak Budi. Jangan lupa kontrol 6 bulan lagi ya",
    lastChatTime: "16:15",
    unreadCount: 0,
    feedbackReview: { rating: 5, komentar: "Hasilnya luar biasa, gigi jadi putih bersih!", tanggal: "2026-04-15" },
    catatanAdmin: "Pasien loyal sejak 2023, berikan layanan prioritas.",
    riwayatPerawatan: [
      { tanggal: "2026-04-15", tindakan: "Whitening Gigi (Laser)", dokter: "drg. Sinta", biaya: 1500000, metode: "Kartu Kredit" },
      { tanggal: "2026-03-20", tindakan: "Konsultasi Whitening", dokter: "drg. Sinta", biaya: 150000, metode: "Tunai" },
      { tanggal: "2025-10-12", tindakan: "Scaling Gigi", dokter: "drg. Amanda", biaya: 350000, metode: "Transfer Bank" },
    ],
    totalTransaksi: 2000000,
    metodePembayaran: "Kartu Kredit",
    jenisPerawatan: "Whitening",
    terakhirKunjungan: "2026-04-15",
    loginTerakhir: "2026-05-27T09:00:00",
    deviceDigunakan: "Windows - Chrome Browser",
    durasiPenggunaan: "20 menit",
    sumberUser: "Rekomendasi Teman",
    campaignDiikuti: ["Promo Whitening 50%", "Member Platinum Benefit"],
    statusPromo: "Tidak Aktif",
    keluhan: "Warna gigi menguning",
    treatment: "Whitening",
    dokter: "drg. Sinta",
    status: "Completed",
    jadwalKontrol: null,
  },
  {
    id: "PS-004",
    nama: "Dewi Kusuma",
    jenisKelamin: "P",
    tanggalLahir: "1998-04-30",
    umur: 28,
    fotoProfil: null,
    noHp: "08122334455",
    email: "dewi.kusuma@gmail.com",
    alamat: "Jl. Hang Tuah No. 3, Siak Sri Indrapura",
    kotaProvinsi: "Siak, Riau",
    tanggalDaftar: "2025-02-14",
    statusMember: "Regular",
    levelMembership: "Bronze",
    statusAktif: false,
    riwayatKomplain: [
      { id: "C-006", tanggal: "2026-05-26", isi: "Biaya perawatan tidak sesuai dengan estimasi awal", status: "Pending", prioritas: "High" },
      { id: "C-007", tanggal: "2026-05-23", isi: "Pasien membatalkan janji tiba-tiba", status: "Pending", prioritas: "Low" },
    ],
    chatHistory: [
      { id: 1, text: "Dok, saya mau reschedule appointment besok", sender: "patient", time: "09:30", tanggal: "2026-05-26" },
      { id: 2, text: "Baik Bu Dewi, kapan Anda available?", sender: "admin", time: "09:35", tanggal: "2026-05-26" },
      { id: 3, text: "Minggu depan kalau bisa", sender: "patient", time: "09:40", tanggal: "2026-05-26" }
    ],
    lastChatMessage: "Minggu depan kalau bisa",
    lastChatTime: "09:40",
    unreadCount: 2,
    feedbackReview: null,
    catatanAdmin: "Pasien sering reschedule, konfirmasi ulang H-1.",
    riwayatPerawatan: [
      { tanggal: "2026-05-22", tindakan: "Konsultasi Cabut Gigi", dokter: "drg. Reza", biaya: 150000, metode: "Tunai" },
    ],
    totalTransaksi: 150000,
    metodePembayaran: "Tunai",
    jenisPerawatan: "Cabut Gigi",
    terakhirKunjungan: "2026-05-22",
    loginTerakhir: "2026-05-22T11:45:00",
    deviceDigunakan: "Android - Xiaomi Redmi Note 12",
    durasiPenggunaan: "10 menit",
    sumberUser: "TikTok",
    campaignDiikuti: [],
    statusPromo: "Tidak Aktif",
    keluhan: "Sakit gigi geraham bawah",
    treatment: "Cabut Gigi",
    dokter: "drg. Reza",
    status: "Cancel",
    jadwalKontrol: { tanggal: "2026-06-05", keterangan: "Reschedule Cabut Gigi" },
  },
  {
    id: "PS-005",
    nama: "Rizky Firmansyah",
    jenisKelamin: "L",
    tanggalLahir: "2003-08-17",
    umur: 22,
    fotoProfil: null,
    noHp: "089512345678",
    email: "rizky.firman@outlook.com",
    alamat: "Jl. Diponegoro No. 45, Bengkalis",
    kotaProvinsi: "Bengkalis, Riau",
    tanggalDaftar: "2025-11-01",
    statusMember: "Regular",
    levelMembership: "Silver",
    statusAktif: true,
    riwayatKomplain: [
      { id: "C-008", tanggal: "2026-05-25", isi: "Ruang tunggu tidak nyaman dan kurang bersih", status: "In Progress", prioritas: "Low" }
    ],
    chatHistory: [
      { id: 1, text: "Halo dok, jadwal kontrol behel saya kapan?", sender: "patient", time: "07:15", tanggal: "2026-05-29" },
      { id: 2, text: "Halo Rizky, kontrol behel Anda Jumat besok jam 10:00", sender: "admin", time: "07:20", tanggal: "2026-05-29" },
      { id: 3, text: "Siap dok, terima kasih!", sender: "patient", time: "07:25", tanggal: "2026-05-29" }
    ],
    lastChatMessage: "Siap dok, terima kasih!",
    lastChatTime: "07:25",
    unreadCount: 0,
    feedbackReview: { rating: 5, komentar: "Behel terpasang rapi, dokternya berpengalaman!", tanggal: "2026-05-10" },
    catatanAdmin: "Sedang masa aktif behel, kontrol setiap 4 minggu.",
    riwayatPerawatan: [
      { tanggal: "2026-05-10", tindakan: "Kontrol Behel Bulan ke-6", dokter: "drg. Amanda", biaya: 300000, metode: "Transfer Bank" },
      { tanggal: "2026-04-05", tindakan: "Kontrol Behel Bulan ke-5", dokter: "drg. Amanda", biaya: 300000, metode: "Transfer Bank" },
      { tanggal: "2025-11-10", tindakan: "Pemasangan Behel Awal", dokter: "drg. Amanda", biaya: 8000000, metode: "Kartu Kredit" },
    ],
    totalTransaksi: 8600000,
    metodePembayaran: "Transfer Bank",
    jenisPerawatan: "Behel",
    terakhirKunjungan: "2026-05-10",
    loginTerakhir: "2026-05-29T07:15:00",
    deviceDigunakan: "iOS - iPhone 13",
    durasiPenggunaan: "55 menit",
    sumberUser: "YouTube",
    campaignDiikuti: ["Promo Behel Pelajar", "Cicilan 0%"],
    statusPromo: "Aktif",
    keluhan: "Gigi tidak rapi & tonggos",
    treatment: "Behel",
    dokter: "drg. Amanda",
    status: "Active",
    jadwalKontrol: { tanggal: "2026-06-07", keterangan: "Kontrol Behel Bulan ke-7" },
  },
  {
    id: "PS-006",
    nama: "Maya Anggraini",
    jenisKelamin: "P",
    tanggalLahir: "1990-12-25",
    umur: 35,
    fotoProfil: null,
    noHp: "081298765432",
    email: "maya.anggraini@gmail.com",
    alamat: "Jl. Rajawali No. 7, Pekanbaru",
    kotaProvinsi: "Pekanbaru, Riau",
    tanggalDaftar: "2023-05-30",
    statusMember: "Premium",
    levelMembership: "Gold",
    statusAktif: true,
    riwayatKomplain: [],
    feedbackReview: { rating: 4, komentar: "Veneer hasilnya natural dan cantik!", tanggal: "2026-02-28" },
    catatanAdmin: "Pasien estetik, perhatikan detail hasil akhir.",
    riwayatPerawatan: [
      { tanggal: "2026-02-28", tindakan: "Pemasangan Veneer (4 gigi)", dokter: "drg. Sinta", biaya: 6000000, metode: "Kartu Kredit" },
      { tanggal: "2026-01-15", tindakan: "Konsultasi & Mockup Veneer", dokter: "drg. Sinta", biaya: 300000, metode: "Tunai" },
      { tanggal: "2025-08-20", tindakan: "Whitening Sebelum Veneer", dokter: "drg. Sinta", biaya: 1200000, metode: "Transfer Bank" },
    ],
    totalTransaksi: 7500000,
    metodePembayaran: "Kartu Kredit",
    jenisPerawatan: "Veneer",
    terakhirKunjungan: "2026-02-28",
    loginTerakhir: "2026-05-20T16:00:00",
    deviceDigunakan: "macOS - Safari Browser",
    durasiPenggunaan: "25 menit",
    sumberUser: "Instagram",
    campaignDiikuti: ["Beauty & Smile Campaign", "Member Gold Reward"],
    statusPromo: "Aktif",
    keluhan: "Ingin gigi lebih estetik & sempurna",
    treatment: "Veneer",
    dokter: "drg. Sinta",
    status: "Completed",
    jadwalKontrol: { tanggal: "2026-08-28", keterangan: "Kontrol Veneer 6 Bulan" },
  },
  {
    id: "PS-007",
    nama: "Hendra Wijaya",
    jenisKelamin: "L",
    tanggalLahir: "1985-06-10",
    umur: 41,
    fotoProfil: null,
    noHp: "082211223344",
    email: "hendra.w@gmail.com",
    alamat: "Jl. Tuanku Tambusai No. 100, Pekanbaru",
    kotaProvinsi: "Pekanbaru, Riau",
    tanggalDaftar: "2024-03-10",
    statusMember: "Regular",
    levelMembership: "Silver",
    statusAktif: true,
    riwayatKomplain: [
      { tanggal: "2026-04-01", isi: "Sakit setelah perawatan saluran akar", status: "Resolved" },
    ],
    feedbackReview: { rating: 3, komentar: "Prosedurnya lama tapi hasilnya oke.", tanggal: "2026-04-20" },
    catatanAdmin: "Pasien dengan riwayat hipertensi, perlu perhatian khusus saat anestesi.",
    riwayatPerawatan: [
      { tanggal: "2026-04-20", tindakan: "Perawatan Saluran Akar Sesi 3", dokter: "drg. Reza", biaya: 1000000, metode: "Transfer Bank" },
      { tanggal: "2026-04-05", tindakan: "Perawatan Saluran Akar Sesi 2", dokter: "drg. Reza", biaya: 1000000, metode: "Transfer Bank" },
      { tanggal: "2026-03-22", tindakan: "Perawatan Saluran Akar Sesi 1", dokter: "drg. Reza", biaya: 500000, metode: "Tunai" },
    ],
    totalTransaksi: 2500000,
    metodePembayaran: "Transfer Bank",
    jenisPerawatan: "Perawatan Saluran Akar",
    terakhirKunjungan: "2026-04-20",
    loginTerakhir: "2026-05-25T10:30:00",
    deviceDigunakan: "Android - Oppo Reno 8",
    durasiPenggunaan: "15 menit",
    sumberUser: "Google Search",
    campaignDiikuti: ["Promo PSA Terjangkau"],
    statusPromo: "Tidak Aktif",
    keluhan: "Nyeri hebat pada gigi geraham kiri",
    treatment: "Perawatan Saluran Akar",
    dokter: "drg. Reza",
    status: "Completed",
    jadwalKontrol: { tanggal: "2026-07-20", keterangan: "Kontrol Pasca PSA & Pemasangan Crown" },
  },
  {
    id: "PS-008",
    nama: "Fatimah Zahra",
    jenisKelamin: "P",
    tanggalLahir: "2000-09-05",
    umur: 25,
    fotoProfil: null,
    noHp: "087756789012",
    email: "fatimah.zahra@gmail.com",
    alamat: "Jl. Imam Bonjol No. 22, Pekanbaru",
    kotaProvinsi: "Pekanbaru, Riau",
    tanggalDaftar: "2026-04-01",
    statusMember: "Regular",
    levelMembership: "Bronze",
    statusAktif: true,
    riwayatKomplain: [],
    feedbackReview: { rating: 5, komentar: "Konsultasinya sangat informatif dan membantu!", tanggal: "2026-04-05" },
    catatanAdmin: "Pasien baru, masih dalam tahap konsultasi awal.",
    riwayatPerawatan: [
      { tanggal: "2026-04-05", tindakan: "Konsultasi Umum & Pemeriksaan", dokter: "drg. Reza", biaya: 150000, metode: "QRIS" },
    ],
    totalTransaksi: 150000,
    metodePembayaran: "QRIS",
    jenisPerawatan: "Konsultasi",
    terakhirKunjungan: "2026-04-05",
    loginTerakhir: "2026-05-28T19:00:00",
    deviceDigunakan: "Android - Samsung Galaxy A54",
    durasiPenggunaan: "40 menit",
    sumberUser: "Facebook",
    campaignDiikuti: ["Konsultasi Gratis Perdana"],
    statusPromo: "Aktif",
    keluhan: "Ingin konsultasi kesehatan gigi umum",
    treatment: "Konsultasi",
    dokter: "drg. Reza",
    status: "Waiting",
    jadwalKontrol: { tanggal: "2026-06-10", keterangan: "Follow-up Konsultasi & Rencana Perawatan" },
  },
];

const ClinicContext = createContext();

export function ClinicProvider({ children }) {
  const [doctors, setDoctors] = useState(INITIAL_DOCTORS);
  const [patients, setPatients] = useState(INITIAL_PATIENTS);
  const [campaigns, setCampaigns] = useState(INITIAL_CAMPAIGNS);

  return (
    <ClinicContext.Provider value={{ doctors, setDoctors, patients, setPatients, campaigns, setCampaigns }}>
      {children}
    </ClinicContext.Provider>
  );
}

export function useClinic() {
  return useContext(ClinicContext);
}
